services:
  postgres_main:
    image: postgres:16
    container_name: mf_postgres_main
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [mfnet]

  config-server:
    build:
      context: ..
      dockerfile: backend/config/config-server/Dockerfile
    ports:
      - "8079:8079"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8079/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [mfnet]

  eureka-server:
    build:
      context: ..
      dockerfile: backend/eureka/eureka-server/Dockerfile
    ports:
      - "8078:8078"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8078/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 30
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8079"
    depends_on:
      config-server:
        condition: service_healthy
    networks: [mfnet]

  api-gateway:
    build:
      context: ..
      dockerfile: backend/gateway/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8079"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks: [mfnet]

  keycloak:
    stop_grace_period: 30s
    build:
      context: ..
      dockerfile: backend/keycloak/Dockerfile
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_main:5432/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_URL: http://keycloak:8085
      KC_HOSTNAME_ADMIN_URL: http://keycloak:8085
      KC_HOSTNAME_STRICT: "true"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 8085
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_PRODUCTION: "true"
    volumes:
      - ../backend/keycloak:/opt/keycloak/data/import
    ports:
      - "8085:8085"
    depends_on:
      postgres_main:
        condition: service_healthy
    networks:
      - mfnet


  customer-microservice:
    build:
      context: ..
      dockerfile: backend/services/customer-microservice/Dockerfile
    container_name: mf_customer
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8079"
    ports:
      - "8081:8081"
    depends_on:
      postgres_main:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
    networks: [mfnet]

  loan-microservice:
    build:
      context: ..
      dockerfile: backend/services/loan-microservice/Dockerfile
    container_name: mf_loan
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8079"
    ports:
      - "8082:8082"
    depends_on:
      postgres_main:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
    networks: [mfnet]

  accounting-microservice:
    build:
      context: ..
      dockerfile: backend/services/accounting_microservice/Dockerfile
    container_name: mf_accounting
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8079"
    ports:
      - "8086:8086"
    depends_on:
      postgres_main:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
    networks: [mfnet]

  payment-microservice:
    build:
      context: ..
      dockerfile: backend/services/payment-microservice/Dockerfile
    container_name: mf_payment
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8079"
    ports:
      - "8083:8083"
    depends_on:
      postgres_main:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
    networks: [mfnet]

  workers_microservice:
    build:
      context: ..
      dockerfile: backend/services/workers_microservice/Dockerfile
    container_name: mf_workers
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8079"
    ports:
      - "8088:8088"
    depends_on:
      postgres_main:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
    networks: [mfnet]

  frontend:
    build:
      context: ../../../frontend/react-frontend-microfinanciera
      dockerfile: Dockerfile
      target: dev
    container_name: mf_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ../../../frontend/react-frontend-microfinanciera/src:/app/src
      - ../../../frontend/react-frontend-microfinanciera/public:/app/public
      - ../../../frontend/react-frontend-microfinanciera/index.html:/app/index.html
      - ../../../frontend/react-frontend-microfinanciera/vite.config.ts:/app/vite.config.ts
      - ../../../frontend/react-frontend-microfinanciera/tsconfig.json:/app/tsconfig.json
      - ../../../frontend/react-frontend-microfinanciera/tailwind.config.ts:/app/tailwind.config.ts
      - ../../../frontend/react-frontend-microfinanciera/postcss.config.js:/app/postcss.config.js
    depends_on:
      - api-gateway
      - keycloak
    networks:
      - mfnet

volumes:
  pgdata:

networks:
  mfnet:
