server:
  port: 8086

APP_SECURITY_DISABLED: true

# oidc:
#   issuer-uri: http://keycloak-prod:8080/realms/mf

spring:
  application:
    name: accounting_microservice
  datasource:
    # Configuración por defecto para desarrollo o entorno genérico
    url: jdbc:postgresql://postgres_main:5432/ms_accounting
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true # Para desarrollo
    properties:
      hibernate:
        format_sql: true # Para desarrollo
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml # Se ha movido aquí para ser común o sobrescribirse
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/mf # Para desarrollo

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8078/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers # Para desarrollo
  endpoint:
    health:
      show-details: ALWAYS # Para desarrollo

logging:
  level:
    org.springframework: INFO
    com.microfinance: DEBUG # Para desarrollo

---
APP_SECURITY_DISABLED: false
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres_main:5432/ms_accounting
    username: root
    password: root
  jpa:
    show-sql: false # Para producción
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/mf # Para producción

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: NEVER

logging:
  level:
    com.microfinance: info
