server:
  port: 8082

APP_SECURITY_DISABLED: true

spring:
  application:
    name: loan-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/microfinance-microservice-realm

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,circuitbreakerevents
  endpoint:
    health:
      show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      customer-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
      accounting-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3


# ==========================================
# Perfil DEV
# ==========================================
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/ms_loan
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8078/eureka

# ==========================================
# Perfil PROD
# ==========================================
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres_main:5432/ms_loan
    username: root
    password: root
  jpa:
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8085/realms/microfinance-microservice-realm

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8078/eureka