server:
  port: 8083

APP_SECURITY_DISABLED: true

spring:
  application:
    name: payment-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml



springdoc:
  api-docs:
    path: /v3/api-docs-payments
    enabled: true
  swagger-ui:
    path: /swagger-ui-payments.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: ALWAYS

# ==========================================
# Perfil DEV
# ==========================================
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/ms_payment
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8078/eureka

# ==========================================
# Perfil PROD
# ==========================================
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres_main:5432/ms_payment
    username: root
    password: root
  jpa:
    show-sql: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8078/eureka
