server:
  port: 8083

APP_SECURITY_DISABLED: true
# oidc:
#   issuer-uri: http://keycloak-prod:8080/realms/mf 

spring:
  application:
    name: payment-microservice
  datasource:
    url: jdbc:postgresql://postgres_main:5432/ms_payment
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true # Para desarrollo
    properties:
      hibernate:
        format_sql: true # Para desarrollo
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/mf # Para desarrollo

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8078/eureka

springdoc:
  api-docs:
    path: /v3/api-docs-payments
    enabled: true # Para desarrollo
  swagger-ui:
    path: /swagger-ui-payments.html
    enabled: true # Para desarrollo
    tags-sorter: alpha
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env # Para desarrollo
  endpoint:
    health:
      show-details: ALWAYS # Para desarrollo

---
APP_SECURITY_DISABLED: false
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres_main:5432/ms_payment
    username: root
    password: root
  jpa:
    show-sql: false # Para producción
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/mf # Para producción
springdoc:
  api-docs:
    enabled: false # Deshabilitado en producción
  swagger-ui:
    enabled: false # Deshabilitado en producción
management:
  endpoints:
    web:
      exposure:
        include: health,info # Exposición mínima en producción
  endpoint:
    health:
      show-details: NEVER # Detalles no expuestos en producción

# server.port no se sobrescribe aquí porque es el mismo (8083)