server:
  port: 8088

APP_SECURITY_DISABLED: true

spring:
  application:
    name: workers-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/microfinance-microservice-realm

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: ALWAYS


# ==========================================
# PERFIL DEV
# ==========================================
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/ms_workers
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8078/eureka

# 🔥 CONFIG DEV PARA KEYCLOAK DESDE HOST
keycloak:
  url: http://localhost:8085
  realm: microfinance-microservice-realm
  client-id: workers-microservice-client
  client-secret: w1C2X4HuSFqrprXdU5WUsiiCO34Moc73


# ==========================================
# PERFIL PROD (DOCKER)
# ==========================================
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres_main:5432/ms_workers
    username: root
    password: root
  jpa:
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8085/realms/microfinance-microservice-realm

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8078/eureka

# 🔥 CONFIG PROD PARA KEYCLOAK DESDE DOCKER
keycloak:
  url: http://keycloak:8085
  realm: microfinance-microservice-realm
  client-id: workers-microservice-client
  client-secret: w1C2X4HuSFqrprXdU5WUsiiCO34Moc73
