spring.application.name=accounting_microservice

server.port=8086
spring.profiles.active=dev

# Liquibase changelog
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

eureka.client.service-url.defaultZone = http://eureka-server:8078/eureka